apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l631z4et9-nodejs
  janus-idp.io/tekton: l631z4et9-nodejs
  backstage.io/kubernetes-id: l631z4et9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l631z4et9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
